version: '3.8'

services:
  redis:
    image: redis:8.2.1
    container_name: redis-production
    restart: always
    ports:
      - "0.0.0.0:6379:6379"  # Bind to all interfaces, firewall restricts to home network
    volumes:
      - /opt/redis/data:/data
      - ./redis.prod.conf:/usr/local/etc/redis/redis.conf:ro
      - /var/log/redis:/var/log/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run

networks:
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
