version: '3.8'

services:
  redis:
    image: redis:8.2.1
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis-cli:
    image: redis:8.2.1
    container_name: redis-client
    depends_on:
      - redis
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    command: tail -f /dev/null
    profiles:
      - cli

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
