version: '3.8'

services:
  redis:
    image: 'redis:8.2.1'
    container_name: my-redis-with-gui
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped


  redis-gui:
    image: 'redis/redisinsight:latest' # The new, correct image name
    container_name: my-redis-gui
    ports:
      - '5540:5540' # The new, correct port
    volumes:
      - redis-insight-data:/data # Mount volume to /data
    restart: unless-stopped


volumes:
  redis-data:
  redis-insight-data: